### ISSUE TITLE
Mangler Cross-origin-resource sharing header

### ISSUE THREAD

**Issue by svetlnaumova** [Artsdatabanken/Nbic.References#2]
Applikasjonen får ikke tilgang til API fordi den kjører på den andre domene og header mangler.

**Comment by steinho** [comment]
Da skal oppdatert api ha blitt publisert - prøv nå?

**Comment by bjornreppen** [comment]
Var bare innom med Chrome for å sjekke, finner fortsatt ingen header?

![image](https://user-images.githubusercontent.com/281359/69189485-c0cff500-0b1e-11ea-993b-6f0b3fd435a1.png)

**Comment by steinho** [comment]
Testet lokalt - mer får ikke opp vpn og tilgang til referenceapi herifra: fikk headers ok når jeg kjørte følgende script i en browser:

<div class="text-center">
    <h1 class="display-4">CORS Test</h1>
</div>

<div>
    <input type="button" value="Test"
           onclick="requestVal('https://localhost:5001/api/references')" />
    <span id='result'></span>
</div>

<script>
    function requestVal(uri) {
        const resultSpan = document.getElementById('result');

        fetch(uri)
            .then(response => response.json())
            .then(data => resultSpan.innerText = data)
            .catch(error => resultSpan.innerText = 'See F12 Console for error');
    }
</script>

**Comment by steinho** [comment]
`<div class="text-center">
    <h1 class="display-4">CORS Test</h1>
</div>

<div>
    <input type="button" value="Test"
           onclick="requestVal('https://localhost:5001/api/references')" />
    <span id='result'></span>
</div>

<script>
    function requestVal(uri) {
        const resultSpan = document.getElementById('result');

        fetch(uri)
            .then(response => response.json())
            .then(data => resultSpan.innerText = data)
            .catch(error => resultSpan.innerText = 'See F12 Console for error');
    }
</script>`

**Comment by steinho** [comment]
code:
[new 19.txt](https://github.com/Artsdatabanken/Nbic.References/files/3868023/new.19.txt)
